// array = word : ['translate', 'definition', 'example']

const english = {
    bring: ["amener", "to take or carry someone or something to a place or a person, or in the direction of the person speaking", "brought", "Bring me that book", "I brought my daughter to the office"],
    get: ["obtenir", "To obtain, buy, or earn something", "Got", "He went to the shop to get some milk", "Where did you get your shoes from"],
    hold: ["tenir",
    "To take and keep something in your hand or arms",
    "Held",
    "Can you hold the bag while I open the door?",
    "The little girl held her mother's hand"],
    stand: ["etre debout",
    "To be in a vertical state or to put into a vertical state, especially (of a person or animal) by making the legs straight",
    "stood",
    "It was time to stand on her own two feet",
    "If you don't stand up and demand a change, he'll keep on doing it"],

    put: ["mettre",
    "To move something or someone into the stated place, position, or direction",
    "put",
    "She put her bag on the table",
    "She puts her name in all her books"],
    make: ["fabriquer",
    "To produce something, often using a particular substance or material",
    "made",
    "He made a chocolate cake",
    "The kids made a real mess in the kitchen"],
    feel: ["sentir",
    "To experience something physical or emotional",
    "felt",
    "How would you feel about moving to a different city?",
    "He felt sick to his stomach again."],
};